.PHONY: all clean

all:
	$(MAKE) -C AlarmService all
	$(MAKE) -C Fibonacci all
	$(MAKE) -C LoadBalance all
	$(MAKE) -C Transaction all
	$(MAKE) -C Transaction_Filter all
	$(MAKE) -C WorldHello all

clean:
	$(MAKE) -C AlarmService clean
	$(MAKE) -C Fibonacci clean
	$(MAKE) -C LoadBalance clean
	$(MAKE) -C Transaction clean
	$(MAKE) -C Transaction_Filter clean
	$(MAKE) -C WorldHello clean

